apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-sidecar
  namespace: myapp-dev
spec:
  containers:
    - name: myapp
      image: <YOUR_DOCKERHUB_USERNAME>/myapp:6.0
      volumeMounts:
        - name: logs
          mountPath: /app/logs
    - name: log-shipper            # sidecar
      image: busybox:1.36
      command: ["sh", "-c", "tail -f /logs/app.log"]
      volumeMounts:
        - name: logs
          mountPath: /logs
  volumes:
    - name: logs
      emptyDir: {}
