replicaCount: 3

image:
  repository: myapp
  pullPolicy: IfNotPresent
  tag: "6.0"

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

livenessProbe:
  httpGet:
    path: /health
    port: 5000
readinessProbe:
  httpGet:
    path: /health
    port: 5000
