FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
ENV APP_NAME=DefaultApp
ENV APP_ENV=development
ENV APP_VERSION=6.0
EXPOSE 5000
CMD ["python", "app.py"]
