apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-demo
  namespace: myapp-dev
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
