apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-prod
resources:
  - ../../base
namePrefix: prod-
images:
  - name: myapp
    newTag: "v1.0"
replicas:
  - name: myapp-deployment
    count: 5
patches:
  - path: patch-replicas.yaml
configMapGenerator:
  - name: myapp-config
    behavior: merge
    literals:
      - APP_ENV=prod
      - LOG_LEVEL=WARN
