apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: myapp-dev
type: Opaque
data:
  DB_PASSWORD: c3VwZXJzZWNyZXQxMjM=
  API_KEY: YWJjLXh5ei03ODk=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: myapp-dev
type: Opaque
stringData:
  POSTGRES_DB: myappdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: secret123
